# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


# from PyQt6 import QtCore, QtGui, QtWidgets

import glob

from PySide6 import QtCore, QtWidgets
from PySide6.QtGui import QStandardItem, QStandardItemModel


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(822, 501)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1091, 491))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_inpaint = QtWidgets.QWidget()
        self.tab_inpaint.setObjectName("tab_inpaint")
        self.widget = QtWidgets.QWidget(self.tab_inpaint)
        self.widget.setGeometry(QtCore.QRect(20, 0, 781, 451))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.listView_tiffImages = QtWidgets.QListView(self.frame)
        self.listView_tiffImages.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.listView_tiffImages.setObjectName("listView_tiffImages")

        listModel = QStandardItemModel()
        tiff_img_directory = "..\img\distorted_images\\"

        for tiff_file in glob.glob(tiff_img_directory + "*.png"):
            print(tiff_file)
            item = QStandardItem((tiff_file))
            listModel.appendRow(item)

        self.listView_tiffImages.setModel(listModel)
        # self.listView_tiffImages.setRootIndex(listModel.setRootPath(tiff_img_directory))

        self.verticalLayout_3.addWidget(self.listView_tiffImages)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.comboBox_6 = QtWidgets.QComboBox(self.frame)
        self.comboBox_6.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout_3.addItem(spacerItem1)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_3.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_3.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_3.addWidget(self.pushButton_12)
        self.horizontalLayout.addWidget(self.frame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.graphicsView = QtWidgets.QGraphicsView(self.widget)
        self.graphicsView.setMaximumSize(QtCore.QSize(500, 500))
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.tabWidget.addTab(self.tab_inpaint, "")
        self.tab_download = QtWidgets.QWidget()
        self.tab_download.setObjectName("tab_download")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_download)
        self.comboBox_5.setGeometry(QtCore.QRect(10, 30, 230, 22))
        self.comboBox_5.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_5 = QtWidgets.QLabel(self.tab_download)
        self.label_5.setGeometry(QtCore.QRect(10, 8, 230, 16))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab_download, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tab_inpaint.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Seleccionar imágen:"))
        self.label_6.setText(_translate("MainWindow", "Escoger método de inpainting:"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Navier Stokes"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Biharmonic"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "Telea"))
        self.pushButton_10.setText(_translate("MainWindow", "Fijar Región"))
        self.pushButton_11.setText(_translate("MainWindow", "Definir máscara"))
        self.pushButton_12.setText(_translate("MainWindow", "Ejecutar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_inpaint), _translate("MainWindow", "Aplicar inpainting"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "USGS"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Planet"))
        self.label_5.setText(_translate("MainWindow", "Escoger proveedor:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_download), _translate("MainWindow", "Obtener imágenes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
